version: "3"
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch01
    ports: 
      - "9200:9200"
      - "9300:9300"
   
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana01:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana01
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:9200
    networks:
      - elastic

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - elastic
    volumes:
      - postgres-data:/var/lib/postgresql/data
    mem_limit: 4g
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          memory: 2g
          cpus: '1.0'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - elastic

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - elastic
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@postgres:5432/mydatabase?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - elastic

  elasticsearch-exporter:
    image: justwatch/elasticsearch_exporter:latest
    container_name: elasticsearch-exporter
    ports:
      - "9114:9114"
    environment:
      - ES_URI=http://elasticsearch01:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  alertmanager-data:
  postgres-data:
  esdata:
  grafana-storage: